"""empty message

Revision ID: b46a47e443ac
Revises: ab094300906b
Create Date: 2025-05-30 01:10:17.077531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46a47e443ac'
down_revision = 'ab094300906b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_name'))
        batch_op.create_index(batch_op.f('ix_authors_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_name'))
        batch_op.create_index(batch_op.f('ix_authors_name'), ['name'], unique=False)

    # ### end Alembic commands ###
